"""POET: Paired Open-Ended Trailblazer -- Co-Evolution of Tasks and Agents.

Implements a simplified POET-like algorithm (Wang et al., 2019) where
environment genomes and agent genomes co-evolve.  New environments are
generated by mutating existing ones; agents from one environment are
periodically tested on others (transfer) to prevent over-specialisation.

Key components
--------------
EnvironmentGenome
    Evolvable parameter vector that parameterises a task (difficulty,
    terrain, obstacle density, etc.).  Users subclass or configure it.

EnvironmentCriterion
    Filters environments: rejects those that are too easy OR too hard for
    the current agent population (Minimal Criterion for environments).

POETPair
    Active (environment, agent) pair with fitness history.

POETArchive
    Manages the set of active pairs, environment reproduction, agent
    transfer, and pair selection.

train_poet
    Standalone co-evolution loop.

Usage::

    from yane.evolution.poet import (
        EnvironmentGenome, EnvironmentCriterion, POETArchive, train_poet
    )

    def eval_fn(agent, env):
        # evaluate agent in env; return scalar fitness
        return -sum((a - b)**2 for a, b in zip(agent.forward(env.params), [0.5]*2))

    def mutate_fn(genome):
        child = genome.copy()
        child.mutate()
        return child

    archive = train_poet(
        eval_fn=eval_fn,
        mutate_agent_fn=mutate_fn,
        initial_env_params=[0.5, 0.5],
        n_generations=50,
        archive_size=10,
    )
    best = archive.best_pair()

Note
----
The LunarLander benchmark and full Gym integration are deferred (require
optional gym dependency).  The spike in ``evolution/experimental.py``
(``CoevolutionPair``, ``CoevolutionPool``) is superseded by this module.
"""
from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Callable

if TYPE_CHECKING:
    from yane.core.genome import Genome


# ---------------------------------------------------------------------------
# EnvironmentGenome
# ---------------------------------------------------------------------------

class EnvironmentGenome:
    """An evolvable parameter vector that defines one task instance.

    Parameters are stored as a flat list of floats.  The vector is clipped to
    ``param_bounds`` after mutation.

    Parameters
    ----------
    params:
        Initial environment parameters.
    param_bounds:
        ``(min, max)`` bounds applied after each mutation.  ``None`` = unbounded.
    mutation_sigma:
        Standard deviation for Gaussian weight mutation.
    env_id:
        Unique integer ID (auto-assigned if ``None``).
    parent_id:
        ID of the parent environment (``None`` for initial environments).
    """

    _id_counter: int = 0

    def __init__(
        self,
        params: "list[float]",
        param_bounds: "tuple[float, float] | None" = None,
        mutation_sigma: float = 0.1,
        env_id: "int | None" = None,
        parent_id: "int | None" = None,
    ) -> None:
        self.params: list[float] = list(params)
        self.param_bounds = param_bounds
        self.mutation_sigma = mutation_sigma
        EnvironmentGenome._id_counter += 1
        self.env_id: int = env_id if env_id is not None else EnvironmentGenome._id_counter
        self.parent_id: int | None = parent_id

    def mutate(self, sigma: "float | None" = None) -> "EnvironmentGenome":
        """Return a mutated copy of this environment genome."""
        s = sigma if sigma is not None else self.mutation_sigma
        new_params = [p + random.gauss(0.0, s) for p in self.params]
        if self.param_bounds is not None:
            lo, hi = self.param_bounds
            new_params = [max(lo, min(hi, p)) for p in new_params]
        return EnvironmentGenome(
            params=new_params,
            param_bounds=self.param_bounds,
            mutation_sigma=self.mutation_sigma,
            parent_id=self.env_id,
        )

    def copy(self) -> "EnvironmentGenome":
        """Return an identical copy (different env_id)."""
        return EnvironmentGenome(
            params=list(self.params),
            param_bounds=self.param_bounds,
            mutation_sigma=self.mutation_sigma,
            parent_id=self.parent_id,
        )

    def __repr__(self) -> str:
        return f"EnvironmentGenome(id={self.env_id}, params={self.params!r})"


# ---------------------------------------------------------------------------
# EnvironmentCriterion
# ---------------------------------------------------------------------------

class EnvironmentCriterion:
    """Filters environments by difficulty for the current agent population.

    An environment is accepted if the best agent achieves fitness between
    ``lower_bound`` and ``upper_bound``.  Too easy (> upper_bound) or too
    hard (< lower_bound) environments are rejected.

    Parameters
    ----------
    lower_bound:
        Minimum fitness the best agent must achieve (environment not too hard).
    upper_bound:
        Maximum fitness the best agent may achieve (environment not too easy).
        ``None`` = no upper bound.
    """

    def __init__(
        self,
        lower_bound: float = -float("inf"),
        upper_bound: "float | None" = None,
    ) -> None:
        self.lower_bound = lower_bound
        self.upper_bound = upper_bound

    def accepts(self, fitness: float) -> bool:
        """Return True iff *fitness* satisfies the criterion."""
        if fitness < self.lower_bound:
            return False  # too hard
        if self.upper_bound is not None and fitness > self.upper_bound:
            return False  # too easy
        return True


# ---------------------------------------------------------------------------
# POETPair
# ---------------------------------------------------------------------------

@dataclass
class POETPair:
    """An active (environment, agent) pair in the POET archive.

    Attributes
    ----------
    env:
        The environment genome.
    agent:
        The agent genome (YANE :class:`~yane.core.genome.Genome`).
    fitness_history:
        Recorded fitness values over generations.
    best_fitness:
        Best fitness ever achieved by this agent in this environment.
    """
    env: EnvironmentGenome
    agent: "Genome"
    fitness_history: list[float] = field(default_factory=list)
    best_fitness: float = -float("inf")

    def record_fitness(self, fitness: float) -> None:
        self.fitness_history.append(fitness)
        if fitness > self.best_fitness:
            self.best_fitness = fitness

    @property
    def current_fitness(self) -> float:
        return self.fitness_history[-1] if self.fitness_history else -float("inf")


# ---------------------------------------------------------------------------
# POETArchive
# ---------------------------------------------------------------------------

class POETArchive:
    """Manages the active set of POET (environment, agent) pairs.

    Parameters
    ----------
    max_size:
        Maximum number of active pairs.
    criterion:
        :class:`EnvironmentCriterion` for filtering candidate environments.
    transfer_interval:
        Number of generations between agent transfer attempts.
    transfer_k:
        Number of agents to test on each target environment during transfer.
    env_children_per_gen:
        Number of child environments produced per generation per active pair.
    """

    def __init__(
        self,
        max_size: int = 10,
        criterion: "EnvironmentCriterion | None" = None,
        transfer_interval: int = 5,
        transfer_k: int = 5,
        env_children_per_gen: int = 2,
    ) -> None:
        self.max_size = max_size
        self.criterion = criterion or EnvironmentCriterion()
        self.transfer_interval = transfer_interval
        self.transfer_k = transfer_k
        self.env_children_per_gen = env_children_per_gen
        self.pairs: list[POETPair] = []
        self.generation: int = 0
        # History of mean fitness per generation
        self.mean_fitness_history: list[float] = []

    # ------------------------------------------------------------------
    # Core operations
    # ------------------------------------------------------------------

    def add(self, pair: POETPair) -> bool:
        """Add *pair* to the archive if there is room.

        Returns ``True`` if added, ``False`` if the archive is full.
        """
        if len(self.pairs) >= self.max_size:
            return False
        self.pairs.append(pair)
        return True

    def remove_weakest(self) -> "POETPair | None":
        """Remove and return the pair with the lowest current fitness."""
        if not self.pairs:
            return None
        worst = min(self.pairs, key=lambda p: p.current_fitness)
        self.pairs.remove(worst)
        return worst

    def reproduce_environments(
        self,
        eval_fn: "Callable[[Genome, EnvironmentGenome], float]",
        mutation_sigma: "float | None" = None,
    ) -> list[POETPair]:
        """Mutate existing environments and add accepted ones to the archive.

        For each active pair, produces ``env_children_per_gen`` child
        environments.  Each child is evaluated against the parent's agent;
        only those passing the :class:`EnvironmentCriterion` are added.

        Returns the list of newly accepted pairs.
        """
        new_pairs: list[POETPair] = []
        for pair in list(self.pairs):
            for _ in range(self.env_children_per_gen):
                child_env = pair.env.mutate(sigma=mutation_sigma)
                fitness = eval_fn(pair.agent, child_env)
                if self.criterion.accepts(fitness):
                    new_pair = POETPair(
                        env=child_env,
                        agent=pair.agent.copy(),
                    )
                    new_pair.record_fitness(fitness)
                    if len(self.pairs) < self.max_size:
                        self.pairs.append(new_pair)
                        new_pairs.append(new_pair)
                    elif new_pair.best_fitness > self.pairs[-1].best_fitness:
                        # Replace weakest
                        self.pairs.remove(min(self.pairs, key=lambda p: p.best_fitness))
                        self.pairs.append(new_pair)
                        new_pairs.append(new_pair)
        return new_pairs

    def transfer_agents(
        self,
        eval_fn: "Callable[[Genome, EnvironmentGenome], float]",
    ) -> int:
        """Try agents from other pairs on each pair's environment.

        For each target pair, randomly samples ``transfer_k`` agents from
        other pairs and evaluates them on the target environment.  If a
        transferred agent outperforms the current agent, it replaces it.

        Returns the number of successful transfers.
        """
        if len(self.pairs) < 2:
            return 0
        n_transfers = 0
        for target in self.pairs:
            candidates = [p.agent for p in self.pairs if p is not target]
            sample_k = min(self.transfer_k, len(candidates))
            sampled = random.sample(candidates, sample_k)
            for candidate_agent in sampled:
                fitness = eval_fn(candidate_agent, target.env)
                if fitness > target.current_fitness:
                    target.agent = candidate_agent.copy()
                    target.record_fitness(fitness)
                    n_transfers += 1
                    break
        return n_transfers

    def step(
        self,
        eval_fn: "Callable[[Genome, EnvironmentGenome], float]",
        mutate_agent_fn: "Callable[[Genome], Genome]",
    ) -> None:
        """Run one POET generation step.

        1. Evaluate all pairs with their own agent and record fitness.
        2. Mutate agents within each pair.
        3. Every ``transfer_interval`` generations: transfer agents.
        4. Every ``transfer_interval`` generations: reproduce environments.
        """
        # 1. Evaluate current pairs
        for pair in self.pairs:
            fitness = eval_fn(pair.agent, pair.env)
            pair.record_fitness(fitness)

        if self.pairs:
            self.mean_fitness_history.append(
                sum(p.current_fitness for p in self.pairs) / len(self.pairs)
            )

        # 2. Mutate agents within each pair
        for pair in self.pairs:
            candidate = mutate_agent_fn(pair.agent)
            candidate_fitness = eval_fn(candidate, pair.env)
            if candidate_fitness > pair.current_fitness:
                pair.agent = candidate
                pair.record_fitness(candidate_fitness)

        # 3 + 4. Periodic transfer and environment reproduction
        if self.generation > 0 and self.generation % self.transfer_interval == 0:
            self.transfer_agents(eval_fn)
            self.reproduce_environments(eval_fn)

        self.generation += 1

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def best_pair(self) -> "POETPair | None":
        """Return the pair with the highest best_fitness."""
        if not self.pairs:
            return None
        return max(self.pairs, key=lambda p: p.best_fitness)

    def __len__(self) -> int:
        return len(self.pairs)

    def __repr__(self) -> str:
        return (
            f"POETArchive(pairs={len(self.pairs)}, "
            f"gen={self.generation}, "
            f"best={self.best_pair().best_fitness if self.pairs else 'N/A'})"
        )


# ---------------------------------------------------------------------------
# Standalone training loop
# ---------------------------------------------------------------------------

@dataclass
class POETResult:
    """Result of :func:`train_poet`.

    Attributes
    ----------
    archive:
        Final :class:`POETArchive`.
    best_pair:
        Pair with the highest ever fitness.
    n_generations:
        Total POET generations run.
    mean_fitness_history:
        Mean fitness of the archive per generation.
    """
    archive: POETArchive
    best_pair: "POETPair | None"
    n_generations: int
    mean_fitness_history: list[float]


def train_poet(
    eval_fn: "Callable[[Genome, EnvironmentGenome], float]",
    mutate_agent_fn: "Callable[[Genome], Genome]",
    initial_env_params: "list[float]",
    initial_agent: "Genome | None" = None,
    n_generations: int = 100,
    archive_size: int = 10,
    env_bounds: "tuple[float, float] | None" = None,
    env_mutation_sigma: float = 0.1,
    criterion: "EnvironmentCriterion | None" = None,
    transfer_interval: int = 5,
    transfer_k: int = 5,
    env_children_per_gen: int = 2,
    seed: "int | None" = None,
) -> POETResult:
    """Run POET co-evolution for *n_generations*.

    Parameters
    ----------
    eval_fn:
        ``(agent, env) -> float`` — evaluates an agent in an environment.
    mutate_agent_fn:
        ``(genome) -> genome`` — produces a mutated copy of an agent genome.
    initial_env_params:
        Parameter vector for the initial environment.
    initial_agent:
        Initial agent genome.  If ``None``, a fresh genome is constructed
        by calling ``mutate_agent_fn`` on itself (identity-safe).
    n_generations:
        Number of POET step() iterations.
    archive_size:
        Maximum active pairs in the archive.
    env_bounds:
        ``(min, max)`` bounds applied to environment parameters after mutation.
    env_mutation_sigma:
        Sigma for environment genome mutation.
    criterion:
        Environment viability criterion.  Default: no upper/lower bound
        (all environments accepted).
    transfer_interval:
        Generations between agent transfer and env reproduction.
    transfer_k:
        Agents tested per target pair during transfer.
    env_children_per_gen:
        Child environments produced per pair per generation.
    seed:
        Random seed for reproducibility.

    Returns
    -------
    POETResult
    """
    if seed is not None:
        random.seed(seed)

    archive = POETArchive(
        max_size=archive_size,
        criterion=criterion or EnvironmentCriterion(),
        transfer_interval=transfer_interval,
        transfer_k=transfer_k,
        env_children_per_gen=env_children_per_gen,
    )

    # Initial environment and agent
    env0 = EnvironmentGenome(
        params=initial_env_params,
        param_bounds=env_bounds,
        mutation_sigma=env_mutation_sigma,
    )
    if initial_agent is None:
        raise ValueError("initial_agent must be provided (a configured Genome)")

    fitness0 = eval_fn(initial_agent, env0)
    pair0 = POETPair(env=env0, agent=initial_agent)
    pair0.record_fitness(fitness0)
    archive.add(pair0)

    for _ in range(n_generations):
        archive.step(eval_fn, mutate_agent_fn)

    return POETResult(
        archive=archive,
        best_pair=archive.best_pair(),
        n_generations=n_generations,
        mean_fitness_history=list(archive.mean_fitness_history),
    )
